# Generated by Django 5.2b1 on 2025-03-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0002_resumeskill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumehead',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
