# Generated by Django 5.1.6 on 2025-02-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('output', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('img_url', models.TextField()),
            ],
        ),
    ]
